from typing import Protocol

from ai_service.knowledge.domain.model.document import Document


class IDocumentRepository(Protocol):
    async def persist(self, document: Document) -> Document: ...

    async def find_by_id(self, id: str) -> Document | None: ...

    async def find_all(self) -> list[Document]: ...

    async def update(self, document: Document) -> Document: ...

    async def remove(self, id: str) -> None: ...
