from typing import Protocol

from ai_service.prompt.domain.model.prompt_template import PromptTemplate


class IPromptTemplateRepository(Protocol):
    async def persist(self, template: PromptTemplate) -> PromptTemplate: ...

    async def find_by_name_and_version(self, name: str, version: int) -> PromptTemplate | None: ...

    async def find_all_by_name(self, name: str) -> list[PromptTemplate]: ...

    async def find_active(self, name: str) -> PromptTemplate | None: ...

    async def find_active_for_user(self, name: str, user_id: str) -> PromptTemplate | None: ...

    async def deactivate_all_by_name(self, name: str) -> None: ...

    async def deactivate_all_by_name_for_user(self, name: str, user_id: str) -> None: ...

    async def deactivate_active_for_user(self, name: str, user_id: str) -> None: ...

    async def update(self, template: PromptTemplate) -> PromptTemplate: ...
